### ISSUE TITLE
[question] geojson parse

### ISSUE THREAD

**Issue by marti1125** [calvinmetcalf/leaflet-ajax#19]
I am trying to parse this geojson

http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson

   var geojsonLayer = new L.GeoJSON.AJAX("http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson");

SyntaxError: JSON.parse: unexpected end of data

**Comment by calvinmetcalf** [comment]
I actually get two errors, the first one is the important one `XMLHttpRequest cannot load http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson. Origin [your page] is not allowed by Access-Control-Allow-Origin.` basically earthquake.usgs.gov does not have cors enable and it can't be parsed because nothing is being returned, you could try doing it via jsonp `var geojsonLayer = new L.GeoJSON.AJAX("http://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson",{dataType:"jsonp"});` but it looks like they don't have it set up to serve jsonp. 

you best bet is to set up a cors proxy aka a server that will proxy a request but add the headers to allow easy cross usage, there is a package for this in npm called `cors-proxy`

**Comment by marti1125** [comment]
thanks 
I found a possible solution using this

var geojsonLayer = new L.GeoJSON.AJAX("http://www.corsproxy.com/earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson",{onEachFeature:popUp});
